[project]
name = "timekeeper"
version = "1.0.0"
description = "Periodic time & record keeper"
readme = "README.md"
requires-python = ">=3.10"
dependencies = []

[project.scripts]
timekeeper = "timekeeper.cli:main"
